package br.com.senacsp.view;

import java.awt.Color;

public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        lblIcone = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFuncionario = new javax.swing.JMenu();
        mnuCadastrar = new javax.swing.JMenuItem();
        mnuAltExclu = new javax.swing.JMenuItem();
        mnuHoraExtra = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeRedimensionado.jpg"))); // NOI18N

        mnuFuncionario.setText("Funcionarios");
        mnuFuncionario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        mnuCadastrar.setText("Cadastrar");
        mnuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuCadastrar);

        mnuAltExclu.setText("Alterar / Excluir");
        mnuAltExclu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltExcluActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuAltExclu);

        mnuHoraExtra.setText("Hora Extra");
        mnuHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHoraExtraActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuHoraExtra);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuSair);

        jMenuBar1.add(mnuFuncionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIcone)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarActionPerformed
        Cadastrar cadastrar = new Cadastrar();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarActionPerformed

    private void mnuAltExcluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltExcluActionPerformed
        TelaIntermediaria intermediaria =  new TelaIntermediaria();
        intermediaria.setVisible(true);
    }//GEN-LAST:event_mnuAltExcluActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHoraExtraActionPerformed
        TelaHoraExtra telaExtra =  new TelaHoraExtra();
        telaExtra.setVisible(true);
    }//GEN-LAST:event_mnuHoraExtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JMenuItem mnuAltExclu;
    private javax.swing.JMenuItem mnuCadastrar;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenuItem mnuHoraExtra;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
